### ISSUE TITLE
Not detecting i3wm on manjaro correctly

### ISSUE THREAD

**Issue by UlisseMini** [reujab/wallpaper#5]
My output from `env` [is here](https://pastebin.com/EhXFxUbu)
from what i can see `DESKTOP_SESSION` and `KDG_CURRENT_DESKTOP` are unset (this is what causes the message)

think detection could be implemented by checking first the environment  then if thats empty checking if the process "i3" is running.

[this](https://stackoverflow.com/questions/15204162/check-if-a-process-exists-in-go-way) or [this](https://stackoverflow.com/questions/374997/find-pid-of-a-process-by-name-without-using-popen-or-system) could help, i'll also try and find a fix myself and if i do i'll pr it :)
EDIT: possible fix on linux, looking in /proc

The code i used to test your library is [here](https://pastebin.com/WV5sVUPP)
Cheers!

**Comment by reujab** [comment]
Sorry for the late response.

This *should* be fixed in 9a7446f, but I haven't tested it on i3. If you could tell me if that commit fixed your issue, that would be great.

**Comment by UlisseMini** [comment]
it detects i3 correctly! i was testing it with `wallpaper.Get` and it looks like you forgot to implement that for i3 (it lives in ~/.config/wall.png for me so you could just return that lacking a better way)

SetFromFile is working, and so is SetFromURL except SetFromURL is returning an 
exec.ExitError from feh (exit status 1), except it changed the wallpaper just fine. i'm not sure why this happens you might want to document it as a bug / ignore exit status 1 errors from feh

**Comment by reujab** [comment]
`Get` is not supported for i3 because I don't think it's actually possible. Feh is only one way of setting the background of an i3 desktop.

I will consider ignoring failing exit statuses from feh.

**Comment by reujab** [comment]
I was just thinking about this issue earlier today because I was curious as to why `feh` is exiting with that status. What is the output of `feh --bg-fill $FILE`?
